[phases.setup]
nixPkgs = ['..', 'jdk17']

[phases.build]
cmds = [
  'cd backend',
  'mvn clean package -DskipTests'
]

[phases.start]
cmd = 'cd backend && java -jar -Dspring.profiles.active=railway -Dserver.port=$PORT -Dlogging.level.com.artwork=DEBUG target/artwork-ecommerce-1.0.0.jar'